// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rodnie.API.Data;

#nullable disable

namespace Rodnie.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250929090936_MigrateAll")]
    partial class MigrateAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rodnie.API.Models.Pin", b =>
                {
                    b.Property<Guid>("pin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("owner_user_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("pin_id");

                    b.HasIndex("owner_user_id");

                    b.ToTable("Pins");
                });

            modelBuilder.Entity("Rodnie.API.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("is_restricted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_verified")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("role")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("сreated_at")
                        .HasColumnType("datetime");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rodnie.API.Models.Pin", b =>
                {
                    b.HasOne("Rodnie.API.Models.User", null)
                        .WithMany()
                        .HasForeignKey("owner_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
